package com.example.periodictable.model

import com.example.periodictable.R


// Code with ❤️
//┌──────────────────────────┐
//│ Created by Eray Belli       │
//│ ──────────────────────── │
//│ erybelli@gmail.com                 │            
//│ ──────────────────────── │
//│ 18.09.2021                  │
//└──────────────────────────┘    

object DummyData {

   val listOfElement = listOf(
    //1 Column

       ElementsModel("",""," "),
       ElementsModel("1","Hidrojen","H",backGroundColor = R.color.firsColumnBack,textColor = R.color.firstColumnText),
       ElementsModel("3","Lityum","Li", backGroundColor = R.color.firsColumnBack,textColor = R.color.firstColumnText),
       ElementsModel("11","Soydyum","Na", backGroundColor = R.color.firsColumnBack,textColor = R.color.firstColumnText),
       ElementsModel("19","Potasyum","K",backGroundColor = R.color.firsColumnBack,textColor = R.color.firstColumnText),
       ElementsModel("37","Rubidyum","Rb",backGroundColor = R.color.firsColumnBack,textColor = R.color.firstColumnText),
       ElementsModel("55","Cesium","Cs",backGroundColor = R.color.firsColumnBack,textColor = R.color.firstColumnText),
       ElementsModel("87","Francium","Fr",backGroundColor = R.color.firsColumnBack,textColor = R.color.firstColumnText),
       ElementsModel("","",""),
       ElementsModel("","",""),
       ElementsModel("","",""),
       // 1 Column End
       // 2 Column
       ElementsModel("","",""),
      ElementsModel("","",""),
    ElementsModel("4","Berilium","Be",backGroundColor = R.color.secondColumnBack,textColor=R.color.secondColumnText),
       ElementsModel("12","Magnesium","Mg",backGroundColor = R.color.secondColumnBack,textColor=R.color.secondColumnText),
       ElementsModel("20","Calsium","Ca",backGroundColor = R.color.secondColumnBack,textColor=R.color.secondColumnText),
       ElementsModel("38","Strontium","Sr",backGroundColor = R.color.secondColumnBack,textColor=R.color.secondColumnText),
       ElementsModel("56","Barium","Ba",backGroundColor = R.color.secondColumnBack,textColor=R.color.secondColumnText),
       ElementsModel("88", "Radium","Ra",backGroundColor = R.color.secondColumnBack,textColor=R.color.secondColumnText),
       ElementsModel("","",""),
       ElementsModel("","",""),
      ElementsModel("","",""),
       // 2 Column End
       // 3 Column,
       ElementsModel("","",""),
       ElementsModel("","",""),
       ElementsModel("","",""),
     ElementsModel("","",""),
    ElementsModel("21","Scandium","Sc",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("39","Yttrium","Y",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText ) ,
       ElementsModel("71","Lutetium","Lu",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText ),
       ElementsModel("103","Lawrencium","Lr",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("","",""),
       ElementsModel("57","Lanthanum","La",backGroundColor = R.color.nineBg,textColor = R.color.nineText),
       ElementsModel("89","Actinium","Ac",backGroundColor = R.color.secondColumnBack,textColor = R.color.secondColumnText),
       // 3 Column End
       //4 Column
       ElementsModel("","","",),
       ElementsModel("","",""),
       ElementsModel("","",""),
     ElementsModel("","",""),
    ElementsModel("22","Titanium","Ti",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("40","Zirconium","Zr",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("72","Hafnium","Hf",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("104","Rutherfordium","Rf",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("","",""),
       ElementsModel("58","Cerium","Ce",backGroundColor = R.color.nineBg,textColor = R.color.nineText),
       ElementsModel("90","Thorium","Th",backGroundColor = R.color.secondColumnBack,textColor = R.color.secondColumnText),

       //4 Column End
       //5 Column
       ElementsModel("","",""),
       ElementsModel("","",""),
       ElementsModel("","",""),
      ElementsModel("","",""),
     ElementsModel("23","Vanadium","V",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("41","Niobium","Nb",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("73","Tantalum","Ta",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("105","Dubnium","Db",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("","",""),
       ElementsModel("59","Praseodymium","Pd",backGroundColor = R.color.nineBg,textColor = R.color.nineText),
       ElementsModel("91","Protactinium","Pa",backGroundColor = R.color.secondColumnBack,textColor = R.color.secondColumnText),

       //5 Column End
       //6 Column
       ElementsModel("","",""),
       ElementsModel("","",""),
       ElementsModel("","",""),
       ElementsModel("","",""),
    ElementsModel("24","Chromium","Cr",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("42","Molybdenum","Mo",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("74","Tungsten","W",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("106","Seaborgium","Sg",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("","",""),
       ElementsModel("60","Tungsten","Tu",backGroundColor = R.color.nineBg,textColor = R.color.nineText),
       ElementsModel("92","Uranium","U",backGroundColor = R.color.secondColumnBack,textColor = R.color.secondColumnText),
       //6 Column End
       //
       ElementsModel("","",""),
       ElementsModel("","",""),
       ElementsModel("","",""),
    ElementsModel("","",""),
    ElementsModel("25","Manganese","Mn",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("43","Technetium","Tc",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("75","Rhenium","Re",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("107","Bohrium","Bh",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("","",""),
       ElementsModel("61","Promethium","Pr",backGroundColor = R.color.nineBg,textColor = R.color.nineText),
       ElementsModel("63","Neptunium","Np",backGroundColor = R.color.secondColumnBack,textColor = R.color.secondColumnText),

       ElementsModel("","",""),
       ElementsModel("","",""),
       ElementsModel("","",""),
    ElementsModel("","",""),
    ElementsModel("26","Iron","Fe",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("44","Ruthenium","Ru",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("76","Osmium","Os",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("108","Osmium","Hs",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("","",""),
       ElementsModel("62","Samarium","Sm",backGroundColor = R.color.nineBg,textColor = R.color.nineText),
       ElementsModel("94","Plutonium","Pu",backGroundColor = R.color.secondColumnBack,textColor = R.color.secondColumnText),

       ElementsModel("","",""),
       ElementsModel("","","",),
       ElementsModel("","","",),
       ElementsModel("","",""),
       ElementsModel("27","Cobalt","Co",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("45","Rhodium","Rh",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("77","Iridium","Ir",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("109","Meitnerium","Mt",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("","",""),
       ElementsModel("63","Europium","Eu",backGroundColor = R.color.nineBg,textColor = R.color.nineText),
       ElementsModel("95","Hidrojen","Am",backGroundColor = R.color.secondColumnBack,textColor = R.color.secondColumnText),

       ElementsModel("","",""),
       ElementsModel("","",""),
       ElementsModel("","",""),
       ElementsModel("","",""),
       ElementsModel("28","Nickel","Ni",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("46","Palladium","Pd",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("78","Platinum","Pt",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("110","Darmstadtium","Ds",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("","",""),
       ElementsModel("64","Gadolinium","Gd",backGroundColor = R.color.nineBg,textColor = R.color.nineText),
       ElementsModel("96","Curium","Cm",backGroundColor = R.color.secondColumnBack,textColor = R.color.secondColumnText),

       ElementsModel("","","",),
       ElementsModel("","",""),
       ElementsModel("","",""),
       ElementsModel("","",""),
      ElementsModel("29","Copper","Cu",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("47","Silver","Ag",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("79","Gold","Au",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("111","Roentgenium","Rg",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("","",""),
       ElementsModel("65","Terbium","Tb",backGroundColor = R.color.nineBg,textColor = R.color.nineText),
       ElementsModel("97","Berkelium","Bk",backGroundColor = R.color.secondColumnBack,textColor = R.color.secondColumnText),

       ElementsModel("","",""),
       ElementsModel("","",""),
       ElementsModel("","",""),
      ElementsModel("","",""),
      ElementsModel("30","Zinc","Zn",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("48","Zinc","Cd",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("80","Mercury","Hg",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("112","Copernicium","Cn",backGroundColor = R.color.thirdColumnBack,textColor = R.color.thirdColumnText),
       ElementsModel("","",""),
       ElementsModel("66","Dysprosium","Dy",backGroundColor = R.color.nineBg,textColor = R.color.nineText),
       ElementsModel("98","Californium","Cf",backGroundColor = R.color.secondColumnBack,textColor = R.color.secondColumnText),

       ElementsModel("","",""),
       ElementsModel("","",""),
       ElementsModel("5","Boron","B",backGroundColor = R.color.fourthBg,textColor = R.color.fourtText),
       ElementsModel("13","Aluminium","Al",backGroundColor = R.color.eightBg, textColor = R.color.eightText),
       ElementsModel("31","Galium","Ga",backGroundColor = R.color.eightBg, textColor = R.color.eightText),
       ElementsModel("49","Indium","In",backGroundColor = R.color.eightBg, textColor = R.color.eightText),
       ElementsModel("81","Thallium","Tl",backGroundColor = R.color.eightBg, textColor = R.color.eightText),
       ElementsModel("113","Ununtrium","Uut",backGroundColor = R.color.eightBg, textColor = R.color.eightText),
       ElementsModel("","",""),
       ElementsModel("67","Holmium","Ho",backGroundColor = R.color.nineBg,textColor = R.color.nineText),
       ElementsModel("99","Eistenium","Es",backGroundColor = R.color.secondColumnBack,textColor = R.color.secondColumnText),

       ElementsModel("","",""),
       ElementsModel("","",""),
       ElementsModel("6","Carbon","C",backGroundColor = R.color.fourthBg,textColor = R.color.fourtText),
       ElementsModel("14","Silicon","Si",backGroundColor = R.color.fourthBg,textColor = R.color.fourtText),
       ElementsModel("32","Germanium","Ge",backGroundColor = R.color.fourthBg,textColor = R.color.fourtText),
       ElementsModel("50","Tin","Sn",backGroundColor = R.color.eightBg, textColor = R.color.eightText),
       ElementsModel("82","Lead","Pb",backGroundColor = R.color.eightBg, textColor = R.color.eightText),
       ElementsModel("114","Flerovium","Fl",backGroundColor = R.color.eightBg, textColor = R.color.eightText),
       ElementsModel("","",""),
       ElementsModel("68","Erbium","Er",backGroundColor = R.color.nineBg,textColor = R.color.nineText ),
       ElementsModel("100","Fermium","Fm",backGroundColor = R.color.secondColumnBack,textColor = R.color.secondColumnText),

       ElementsModel("","",""),
       ElementsModel("","",""),
       ElementsModel("7","Nitrogen","N", backGroundColor = R.color.fifthBg, textColor = R.color.fifthText),
       ElementsModel("15","Phosphorus","P", backGroundColor = R.color.fifthBg, textColor = R.color.fifthText),
       ElementsModel("33","Arsenic","As",backGroundColor = R.color.fourthBg,textColor = R.color.fourtText),
       ElementsModel("51","Antimony","Sb",backGroundColor = R.color.fourthBg,textColor = R.color.fourtText),
       ElementsModel("83","Bismuth","Bi",backGroundColor = R.color.eightBg, textColor = R.color.eightText),
       ElementsModel("115","Unupentium","Uup",backGroundColor = R.color.eightBg, textColor = R.color.eightText),
       ElementsModel("","",""),
       ElementsModel("69","Thulium","Tm",backGroundColor = R.color.nineBg,textColor = R.color.nineText),
       ElementsModel("101","Mendelevium","Md",backGroundColor = R.color.secondColumnBack,textColor = R.color.secondColumnText),

       ElementsModel("","","",),
       ElementsModel("","",""),
       ElementsModel("8","Oxygen","O", backGroundColor = R.color.fifthBg, textColor = R.color.fifthText),
       ElementsModel("16","Sulfur","S", backGroundColor = R.color.fifthBg, textColor = R.color.fifthText),
       ElementsModel("34","Selenium","Se", backGroundColor = R.color.fifthBg, textColor = R.color.fifthText),
       ElementsModel("52","Tellurium","Te",backGroundColor = R.color.fourthBg,textColor = R.color.fourtText),
       ElementsModel("84","Polonium","Po",backGroundColor = R.color.fourthBg,textColor = R.color.fourtText),
       ElementsModel("116","Livermorium","Lv",backGroundColor = R.color.fourthBg,textColor = R.color.fourtText),
       ElementsModel("","",""),
       ElementsModel("70","Ytterbium","Yb",backGroundColor = R.color.nineBg,textColor = R.color.nineText),
       ElementsModel("102","Nobelium","No",backGroundColor = R.color.secondColumnBack,textColor = R.color.secondColumnText),

       ElementsModel("","",""),
      ElementsModel("","",""),
    ElementsModel("9","Fluorine","Fl",backGroundColor = R.color.sixthBg, textColor = R.color.sixthText),
       ElementsModel("17","Chlorine","Cl",backGroundColor = R.color.sixthBg, textColor = R.color.sixthText),
       ElementsModel("35","Bromine","Br",backGroundColor = R.color.sixthBg, textColor = R.color.sixthText),
       ElementsModel("53","Iodine","I",backGroundColor = R.color.sixthBg, textColor = R.color.sixthText),
       ElementsModel("85","Astatine","At",backGroundColor = R.color.sixthBg, textColor = R.color.sixthText),
       ElementsModel("117","Tennessine","Te",backGroundColor = R.color.sixthBg, textColor = R.color.sixthText),
       ElementsModel("","",""),
       ElementsModel("71","Lutetium","Lu" ,backGroundColor = R.color.nineBg,textColor = R.color.nineText),
       ElementsModel("103","Lawrencium","Lr",backGroundColor = R.color.secondColumnBack,textColor = R.color.secondColumnText),

       ElementsModel("","",""),
       ElementsModel("2","Helium","He",backGroundColor = R.color.seventhBg, textColor = R.color.seventhText),
       ElementsModel("10","Neon","Ne",backGroundColor = R.color.seventhBg, textColor = R.color.seventhText),
       ElementsModel("18","Argon","Ar",backGroundColor = R.color.seventhBg, textColor = R.color.seventhText),
       ElementsModel("36","Krypton","Kr",backGroundColor = R.color.seventhBg, textColor = R.color.seventhText),
       ElementsModel("54","Xenon","Xe",backGroundColor = R.color.seventhBg, textColor = R.color.seventhText),
       ElementsModel("86","Radon","Rn",backGroundColor = R.color.seventhBg, textColor = R.color.seventhText),
       ElementsModel("118","Oganesson","Uuo",backGroundColor = R.color.seventhBg, textColor = R.color.seventhText),
       ElementsModel("","",""),
       ElementsModel("","",""),
       ElementsModel("","","")

    )
}